### ISSUE TITLE
windows环境运行getRuntimeResult 问题

### ISSUE THREAD

**Issue by 13rj115** [hzxie/voj#21]
Exception in thread "main" java.lang.Error: API:     CreateProcess
Code:    87
Message: ²ÎÊý´íÎó¡
	at org.verwandlung.voj.judger.core.Runner.getRuntimeResult(Native Method)
	at com.zufe.teach.test.main(test.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by hzxie** [comment]
I **CANNOT** reproduce this problem.

According to [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx), Code:87 represents:

```
ERROR_INVALID_PARAMETER
87 (0x57)
The parameter is incorrect.
```

Please offer the logs of judger, which can be find in `logs` directory.
Also please check your `voj.properties` that username and password has been set correctly.
Thank you.

**Comment by 13rj115** [comment]
感谢你的解答，确实是参数问题，我Windows账号密码没设，现在可以运行了。
