### ISSUE TITLE
单独提取JudgerCore.dll使用时抛出找不到文件异常

### ISSUE THREAD

**Issue by Ray-Eldath** [hzxie/voj#25]
若使用**当前登录的用户**和对应的密码（隶属于：`Users, Administrators`）传入`getRuntimeResult`则正常。但若使用新创建的用户和对应的密码（权限完全一致）传入将会抛出异常：
```
2017-07-05 23:18:05  [ main:0 ] - [ INFO ]  Start compiling with command: python -m py_compile G:\executive\1499267885127.py
Exception in thread "main" java.lang.Error: API:     CreateProcess
Code:    2
Message: ϵͳÕҲ»µ½ָ¶¨µÄ
	at org.verwandlung.voj.judger.core.Runner.getRuntimeResult(Native Method)
	at org.verwandlung.voj.judger.core.Runner.getRuntimeResult(Runner.java:111)
	at org.verwandlung.voj.judger.core.Compiler.getCompileResult(Compiler.java:76)
	at org.verwandlung.voj.judger.core.Compiler.getCompileResult(Compiler.java:35)
	at avalon.extend.Executive.execute(Executive.java:40)
	at test.ExecutiveTest.main(ExecutiveTest.java:16)
```
如何解决？

**Comment by hzxie** [comment]
Ref: https://stackoverflow.com/questions/32926272/beginner-c-createprocess-error-2
**Error Code 2** indidates that the system cannot find the file specified.

我认为是不是你的路径: `G:\executive\1499267885127.py` 应该改成 `G:/executive/1499267885127.py` 或者 `G:\\executive\\1499267885127.py`.

**Comment by Ray-Eldath** [comment]
不行。使用路径`G:/executive/...`或`G:\\executive\\`均出现相同错误。

**Comment by hzxie** [comment]
你命令行中可以使用`python`吗？

**Comment by Ray-Eldath** [comment]
可以。
```
F:\Code\Project\Avalon>python
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

< Haozhe Xie<mailto:notifications@github.com>> 在 2017-07-08 12:29:38 写道:

你命令行中可以使用python吗？

**Comment by hzxie** [comment]
那你命令行中使用`python -m py_compile G:\executive\1499267885127.py`这可以执行吗?

**Comment by Ray-Eldath** [comment]
可以的。命令及返回：
C:\Users\lizha>python -m py_compile G:\executive\1499487264574.py
  File "G:\executive\1499487264574.py", line 1
    print 1+1
          ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by hzxie** [comment]
这…… 怎么可能呢……
哦～！我记得配置文件里需要配置Windows的账户和密码，这个你配置了吗？

**Comment by Ray-Eldath** [comment]
**蛤？配置文件？**

我是直接将用户名、密码传入下面这个`native`方法的：
```
public native Map<String, Object> getRuntimeResult(String commandLine,
                                                       String systemUsername,
                                                       String systemPassword,
                                                       String inputFilePath,
                                                       String outputFilePath,
                                                       int timeLimit,
                                                       int memoryLimit);
```

**Comment by hzxie** [comment]
用户名和密码是指你Windows操作系统的用户名和密码。
所以你的意思是你传递了正确的用户名和密码？
那你试试Python之外的语言，可以正常编译和执行吗？

**Comment by hzxie** [comment]
所以？

**Comment by a815191377** [comment]
我自己打包的动态链接库，单元测试报这个错，账号密码已经配置（密码配置错误是1326）。你这里没有最新的dll包，所以我不确定是不是打包的问题
java.lang.Error: API:     CreateProcess
Code:    1058
Message: Î޷¨Æô¶¯·þÎñ£¬ԭÒò¿ÉÄÜÊÇÒѱ»½ûÓûòÓëÆäÏà¹Øjµ
	at org.verwandlung.voj.judger.core.Runner.getRuntimeResult(Native Method)
	at org.verwandlung.voj.judger.core.Runner.getRuntimeResult(Runner.java:187)
	at org.verwandlung.voj.judger.core.Compiler.getCompileResult(Compiler.java:116)
	at org.verwandlung.voj.judger.core.Compiler.getCompileResult(Compiler.java:73)
	at org.verwandlung.voj.judger.core.RunnerTest.testGetRuntimeResultCpp(RunnerTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:436)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:112)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

**Comment by a815191377** [comment]
我是用另外一个管理员级别账号来执行的，不确定你这里是限制低级别用户执行的吗

**Comment by a815191377** [comment]
1058 无法启动服务，原因可能是它被禁用或与它相关联的设备没有启动。

**Comment by a815191377** [comment]
我的已经解决，操作系统权限有差异，我在公司的电脑可以正常操作了
