### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by aekiz** [hzxie/voj#42]
Everything goes fine until Runner.getRuntimeResult  get called. I'm getting this exception. Am I missin smoething?
regards.

- gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)
-java version "1.8.0_121"
-Windows 10

java.lang.UnsatisfiedLinkError: org.verwandlung.voj.judger.core.Runner.getRuntimeResult(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)Ljava/util/Map;
	at org.verwandlung.voj.judger.core.Runner.getRuntimeResult(Native Method) ~[classes/:?]
	at org.verwandlung.voj.judger.core.Runner.getRuntimeResult(Runner.java:187) ~[classes/:?]
	at org.verwandlung.voj.judger.core.Compiler.getCompileResult(Compiler.java:116) ~[classes/:?]
	at org.verwandlung.voj.judger.core.Compiler.getCompileResult(Compiler.java:73) ~[classes/:?]
	at org.verwandlung.voj.judger.core.Dispatcher.compile(Dispatcher.java:140) ~[classes/:?]

JudgerCore.dll was created successfully as seen.

Compile JNI C Library:
     [echo] Generating JNI headers
     [echo] Generating dynamic-link library
     [exec] mkdir target\cpp
     [exec] g++ -c -std=c++11 -Wall -fPIC -I ...  src\main\cpp/windows/Judger.Core.Runner.cpp -o target\cpp/Judger.Core.Runner.o
     [exec] g++ -fPIC -shared target\cpp/Judger.Core.Runner.o -luserenv -lpsapi -o target\classes\JudgerCore.dll
[INFO] Executed tasks

**Comment by hzxie** [comment]
- Is your JDK 64 bit?
- Please open `voj-judger.jar` with WinRAR. Check if there's a file named `JudgerCore.dll` at the ROOT of this file.

**Comment by hzxie** [comment]
Solution: Try to add `JudgerCore.dll` to `voj-judger.jar`.
BTW, you can paste complete building log for further support.
