### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by haitaoya** [hzxie/voj#52]
![image](https://user-images.githubusercontent.com/43179881/57204300-75725100-6fe9-11e9-9d3e-67fc0ced4ef8.png)
#### 点击加载更多提交后，日期的格式有点差异。- -
![image](https://user-images.githubusercontent.com/43179881/57204323-9e92e180-6fe9-11e9-88d7-c8031122d8b9.png)

-----
#### 还有如果试题的唯一ID有过删除的话，ID产生了不连续编号。
那么后台的查询试题分类和试题标签 与 试题信息 无法完全匹配。
试题查询这里是按照`Page`的大小进行查询，比如从1001开始查询到10条，但是其中删除了5条，那么查询到的是`（1001~1015）`
https://github.com/hzxie/voj/blob/954dc58c3a1d79f516fbce81b6d4ed278fbfc9c9/web/src/main/java/org/verwandlung/voj/web/controller/AdministrationController.java#L413
试题分类和试题标签查询是按照当前`ID 1001 到 1001 + pageSize （1010）`的信息。 
https://github.com/hzxie/voj/blob/954dc58c3a1d79f516fbce81b6d4ed278fbfc9c9/web/src/main/java/org/verwandlung/voj/web/controller/AdministrationController.java#L414

最后后台管理显示的试题后边的试题标签和分类信息会显示空白。
这里怎么避免产生不连续的试题ID呢？

**Comment by hzxie** [comment]
1. 更多提交的日期是由JS生成的。之前的日期是由JSP生成的。当年我调试过，两个格式是一致的。一会儿我看一下。因为我一直用英文版的，所以没发现。
2. ID不连续很容易解决，但是一般不这么做。通过该查询的offset就可以。一会儿我看一下。

现在看当年还真的是比较稚嫩。

**Comment by haitaoya** [comment]
嗯嗯，还有我觉得一道试题的 提交数 和 通过数 统计的时候应该同一个用户多次提交只记作一次比较合理吧。
不然试题的AC率感觉不是很精确。

**Comment by hzxie** [comment]
AC率的确是这么算的吧。

**Comment by haitaoya** [comment]
@hzxie 嗯嗯，的确是这么算的。 我理解错误，不好意思  - -#

**Comment by haitaoya** [comment]
直接部署Judger端在Window系统上，怎么保证程序运行时的安全性呀？
如果部署到Docker中是不是可以起到沙箱的作用呢？

**Comment by hzxie** [comment]
Windows上你可以创建一个较低权限的帐户运行评测机。
在配置文件里设置账户的用户名和密码就可以了。

**Comment by haitaoya** [comment]
嗯，好的。

**Comment by haitaoya** [comment]
judge端支持在Windows Server 2008 R2服务器部署吗？
我放在了阿里云服务器上，提交一致system error - -#

**Comment by hzxie** [comment]
支持的。当年测试过。
System Error有日志吗？

**Comment by haitaoya** [comment]
有的。我找下

**Comment by haitaoya** [comment]
```
[INFO] 2019-05-07 21:46:50,287 [ActiveMQ Session Task-3] com.easyoj.judger.messenger.MessageReceiver - Received new submission task #1176
[DEBUG] 2019-05-07 21:46:51,287 [ActiveMQ Session Task-3] org.springframework.jdbc.datasource.DataSourceUtils - Fetching JDBC Connection from DataSource
[DEBUG] 2019-05-07 21:46:51,287 [ActiveMQ Session Task-3] org.springframework.jdbc.datasource.DataSourceUtils - Returning JDBC Connection to DataSource
[DEBUG] 2019-05-07 21:46:51,287 [ActiveMQ Session Task-3] org.springframework.jdbc.datasource.DataSourceUtils - Fetching JDBC Connection from DataSource
[DEBUG] 2019-05-07 21:46:51,302 [ActiveMQ Session Task-3] org.springframework.jdbc.datasource.DataSourceUtils - Returning JDBC Connection to DataSource
[INFO] 2019-05-07 21:46:51,302 [ActiveMQ Session Task-3] com.easyoj.judger.core.Compiler - Start compiling with command: javac -encoding UTF-8 C:/tmp/eoj-1176/BScHhrViKCpr.java
[WARN] 2019-05-07 21:46:51,521 [ActiveMQ Session Task-3] org.springframework.jms.listener.SimpleMessageListenerContainer - Execution of JMS message listener failed, and no ErrorHandler has been set.
java.lang.Error: API:     CreateProcess
Code:    1326
Message: ????°?: δ?????§???ò?í?ó?
	at com.easyoj.judger.core.Runner.getRuntimeResult(Native Method) ~[judger.jar:?]
	at com.easyoj.judger.core.Runner.getRuntimeResult(Runner.java:154) ~[judger.jar:?]
	at com.easyoj.judger.core.Compiler.getCompileResult(Compiler.java:78) ~[judger.jar:?]
	at com.easyoj.judger.core.Compiler.getCompileResult(Compiler.java:35) ~[judger.jar:?]
	at com.easyoj.judger.core.Dispatcher.compile(Dispatcher.java:103) ~[judger.jar:?]
	at com.easyoj.judger.core.Dispatcher.createNewTask(Dispatcher.java:61) ~[judger.jar:?]
	at com.easyoj.judger.application.ApplicationDispatcher.onSubmissionCreated(ApplicationDispatcher.java:33) ~[judger.jar:?]
	at com.easyoj.judger.messenger.MessageReceiver.newSubmissionHandler(MessageReceiver.java:53) ~[judger.jar:?]
	at com.easyoj.judger.messenger.MessageReceiver.onMessage(MessageReceiver.java:32) ~[judger.jar:?]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761) ~[judger.jar:?]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699) ~[judger.jar:?]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[judger.jar:?]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:645) ~[judger.jar:?]
	at org.springframework.jms.listener.SimpleMessageListenerContainer.processMessage(SimpleMessageListenerContainer.java:322) ~[judger.jar:?]
	at org.springframework.jms.listener.SimpleMessageListenerContainer.lambda$createListenerConsumer$2(SimpleMessageListenerContainer.java:299) ~[judger.jar:?]
	at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1404) [judger.jar:?]
	at org.apache.activemq.ActiveMQSessionExecutor.dispatch(ActiveMQSessionExecutor.java:131) [judger.jar:?]
	at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:202) [judger.jar:?]
	at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133) [judger.jar:?]
	at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48) [judger.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_131]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

```
提交之后一直是 `pending` ， 会不会是DLL链接库版本的问题呢...

**Comment by haitaoya** [comment]
......sorry  
我忘记改密码了...服务器的密码和我本机的密码 不一致。。。。

抱歉抱歉抱歉...
![image](https://user-images.githubusercontent.com/43179881/57341129-af6b6080-716b-11e9-8a01-5035101d07b9.png)
这里的错误信息为什么是乱码呢。。。应该是window系统返回的错误信息。
怎么才能正常显示呀？

**Comment by hzxie** [comment]
Windows上编码默认是GBK，我用的应该是UTF-8。
反正自古以来就是乱七八糟的。反正我用英文版，懒得管这些破事儿。
我觉得也不重要吧。根据Error Code一查就知道啦。

**Comment by haitaoya** [comment]
嗯嗯。 好的

**Comment by hzxie** [comment]
有一个建议: 下次能不能每个问题开新的issue。别一直回复。

**Comment by hzxie** [comment]
你最开始的问题我还没解决。

**Comment by haitaoya** [comment]
嗯嗯，我下次注意。

**Comment by everlo** [comment]
感谢作者大大的oj,小弟捣鼓了好久，总算是部署起来了，现在的话我们要增加题目。是通过什么方式操作的呢。貌似没有看到相关页面和接口呢
