### ISSUE TITLE
judge报错 前端卡在Pending

### ISSUE THREAD

**Issue by kevinMintnick** [hzxie/voj#69]
[INFO] 2020-02-07 18:30:33,477 [ActiveMQ Session Task-1] org.verwandlung.voj.judger.core.Compiler - Start compiling with command: g++ -O2 -s -Wall -std=c++11 -o /tmp/voj-1008/IocPckWHjGTe.exe /tmp/voj-1008/IocPckWHjGTe.cpp -lm
**[WARN] 2020-02-07 18:30:33,683 [ActiveMQ Session Task-1] org.springframework.jms.listener.SimpleMessageListenerContainer - Execution of JMS message listener failed, and no ErrorHandler has been set.**
java.lang.Error: API:     CreateProcess
**Code:    1385**
**Message: ????°?: δ???è??§???????ú??????ó????à
        at org.verwandlung.voj.judger.core.Runner.getRuntimeResult(Native Method) ~[voj.judger.jar:?]
        at org.verwandlung.voj.judger.core.Runner.getRuntimeResult(Runner.java:188) ~[voj.judger.jar:?]
        at org.verwandlung.voj.judger.core.Compiler.getCompileResult(Compiler.java:116) ~[voj.judger.jar:?]
        at org.verwandlung.voj.judger.core.Compiler.getCompileResult(Compiler.java:73) ~[voj.judger.jar:?]
        at org.verwandlung.voj.judger.core.Dispatcher.compile(Dispatcher.java:140) ~[voj.judger.jar:?]
        at org.verwandlung.voj.judger.core.Dispatcher.createNewTask(Dispatcher.java:99) ~[voj.judger.jar:?]
        at org.verwandlung.voj.judger.application.ApplicationDispatcher.onSubmissionCreated(ApplicationDispatcher.java:72) ~[voj.judger.jar:?]
        at org.verwandlung.voj.judger.messenger.MessageReceiver.newSubmissionHandler(MessageReceiver.java:92) ~[voj.judger.jar:?]
        at org.verwandlung.voj.judger.messenger.MessageReceiver.onMessage(MessageReceiver.java:71) ~[voj.judger.jar:?]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761) ~[voj.judger.jar:?]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699) ~[voj.judger.jar:?]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[voj.judger.jar:?]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:645) ~[voj.judger.jar:?]
        at org.springframework.jms.listener.SimpleMessageListenerContainer.processMessage(SimpleMessageListenerContainer.java:322) ~[voj.judger.jar:?]
        at org.springframework.jms.listener.SimpleMessageListenerContainer.lambda$createListenerConsumer$2(SimpleMessageListenerContainer.java:299) ~[voj.judger.jar:?]
        at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1404) [voj.judger.jar:?]
        at org.apache.activemq.ActiveMQSessionExecutor.dispatch(ActiveMQSessionExecutor.java:131) [voj.judger.jar:?]
        at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:202) [voj.judger.jar:?]
        at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133) [voj.judger.jar:?]
        at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48) [voj.judger.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]**

**Comment by hzxie** [comment]
Error 1385 is a Windows system error that means the following:

> Logon failure: The user has not been granted the requested logon type at this computer.

Please double-check the username and password in the voj.properties
